//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuVilator.Xam.Forms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuVilator.Xam.Forms.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AuVilator..
        /// </summary>
        internal static string AuVilator_Welcome {
            get {
                return ResourceManager.GetString("AuVilator_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Bin Size.
        /// </summary>
        internal static string BinSizePickerText {
            get {
                return ResourceManager.GetString("BinSizePickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        internal static string BinSizeSelectedLabelText {
            get {
                return ResourceManager.GetString("BinSizeSelectedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select bin size you prefer AuVilator to process the media file. 
        ///Note, Bigger the size of bin means more computation will be performed by AuVilator which makes processing slow. 
        ///Smaller bin size allows to purge more silence as compared to higher size whereas higher size can result in loss of non silence signals..
        /// </summary>
        internal static string BinSizeSelectionInformationText {
            get {
                return ResourceManager.GetString("BinSizeSelectionInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bin Size for Signal Analysis.
        /// </summary>
        internal static string BinSizeSelectionTitleText {
            get {
                return ResourceManager.GetString("BinSizeSelectionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select amplitude value to identify non silent signal. 
        ///Note, AuVilator uses this value to search for the ending point of non silent signal bin. 
        ///Please, Keep in mind that bin size affects these value in direct relation..
        /// </summary>
        internal static string EndAmpPosInformationText {
            get {
                return ResourceManager.GetString("EndAmpPosInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ending Amplitude for Signal.
        /// </summary>
        internal static string EndAmpPosSelectionTitleText {
            get {
                return ResourceManager.GetString("EndAmpPosSelectionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Audio File.
        /// </summary>
        internal static string FileSelectionButtonText {
            get {
                return ResourceManager.GetString("FileSelectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Audio File to Purge Silence.
        /// </summary>
        internal static string FileSelectionTitleText {
            get {
                return ResourceManager.GetString("FileSelectionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stack:.
        /// </summary>
        internal static string Gen_Error_Stack {
            get {
                return ResourceManager.GetString("Gen_Error_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string InformationCloseButtonText {
            get {
                return ResourceManager.GetString("InformationCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationTitleText {
            get {
                return ResourceManager.GetString("InformationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected yet!.
        /// </summary>
        internal static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Silencer.
        /// </summary>
        internal static string RunSilencerButtonText {
            get {
                return ResourceManager.GetString("RunSilencerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any audio or video file to process.
        ///However, AuVilator will only extract audio signals regardless of file format and return results in wav file..
        /// </summary>
        internal static string SelectFileInformationText {
            get {
                return ResourceManager.GetString("SelectFileInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Settings_V_Language_Change_Btn {
            get {
                return ResourceManager.GetString("Settings_V_Language_Change_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string Settings_V_Language_Change_Picker_Title {
            get {
                return ResourceManager.GetString("Settings_V_Language_Change_Picker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_V_Language_TB {
            get {
                return ResourceManager.GetString("Settings_V_Language_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_V_Main_Title {
            get {
                return ResourceManager.GetString("Settings_V_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Silencer_V_Cancel_Btn {
            get {
                return ResourceManager.GetString("Silencer_V_Cancel_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong File Format!.
        /// </summary>
        internal static string SilencerVM_CFF_EX_Caption {
            get {
                return ResourceManager.GetString("SilencerVM_CFF_EX_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected file.
        /// </summary>
        internal static string SilencerVM_CFF_EX_Text_1 {
            get {
                return ResourceManager.GetString("SilencerVM_CFF_EX_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not .wav format..
        /// </summary>
        internal static string SilencerVM_CFF_EX_Text_2 {
            get {
                return ResourceManager.GetString("SilencerVM_CFF_EX_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reselect the file..
        /// </summary>
        internal static string SilencerVM_CFF_EX_Text_3 {
            get {
                return ResourceManager.GetString("SilencerVM_CFF_EX_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading file!.
        /// </summary>
        internal static string SilencerVM_LF_EX_Caption {
            get {
                return ResourceManager.GetString("SilencerVM_LF_EX_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuVilator failed to load the selected file..
        /// </summary>
        internal static string SilencerVM_LF_EX_Text {
            get {
                return ResourceManager.GetString("SilencerVM_LF_EX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Select.
        /// </summary>
        internal static string SilencerVM_LF_MB_No_Selected_Caption {
            get {
                return ResourceManager.GetString("SilencerVM_LF_MB_No_Selected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected!.
        /// </summary>
        internal static string SilencerVM_LF_MB_No_Selected_Text {
            get {
                return ResourceManager.GetString("SilencerVM_LF_MB_No_Selected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string SilencerVM_LF_Select_Picker_Filter_All {
            get {
                return ResourceManager.GetString("SilencerVM_LF_Select_Picker_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files.
        /// </summary>
        internal static string SilencerVM_LF_Select_Picker_Filter_Audio {
            get {
                return ResourceManager.GetString("SilencerVM_LF_Select_Picker_Filter_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .wav file to process..
        /// </summary>
        internal static string SilencerVM_LF_Select_Wav_Title {
            get {
                return ResourceManager.GetString("SilencerVM_LF_Select_Wav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting file save path or name!.
        /// </summary>
        internal static string SilencerVM_SF_EX_Caption {
            get {
                return ResourceManager.GetString("SilencerVM_SF_EX_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuVilator failed to get provided save path or name..
        /// </summary>
        internal static string SilencerVM_SF_EX_Text {
            get {
                return ResourceManager.GetString("SilencerVM_SF_EX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file path or name provided!.
        /// </summary>
        internal static string SilencerVM_SF_MB_No_Selected_Text {
            get {
                return ResourceManager.GetString("SilencerVM_SF_MB_No_Selected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string SilencerVM_SF_Save_Picker_Title {
            get {
                return ResourceManager.GetString("SilencerVM_SF_Save_Picker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Failed!.
        /// </summary>
        internal static string SilencerVM_STA_EX_Caption {
            get {
                return ResourceManager.GetString("SilencerVM_STA_EX_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while processing the given file..
        /// </summary>
        internal static string SilencerVM_STA_EX_Text {
            get {
                return ResourceManager.GetString("SilencerVM_STA_EX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Completed!.
        /// </summary>
        internal static string SilencerVM_STA_MB_Caption {
            get {
                return ResourceManager.GetString("SilencerVM_STA_MB_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your audio file successfully processed!.
        /// </summary>
        internal static string SilencerVM_STA_MB_Text {
            get {
                return ResourceManager.GetString("SilencerVM_STA_MB_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select amplitude value to identify non silent signal. 
        ///Note, AuVilator uses this value to search for the starting point of non silent signal bin. 
        ///Please, Keep in mind that bin size affects these value in direct relation..
        /// </summary>
        internal static string StartAmpPosInformationText {
            get {
                return ResourceManager.GetString("StartAmpPosInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Starting Amplitude for Signal.
        /// </summary>
        internal static string StartAmpPosSelectionTitleText {
            get {
                return ResourceManager.GetString("StartAmpPosSelectionTitleText", resourceCulture);
            }
        }
    }
}
